[tool.poetry]
name = "canviewer"
version = "0.0.1"
description = "CAN Sender GUI with slcand"
authors = ["tomixrm <chocolate0785lego@icloud.com>"]
license = "LGPL-2.1"
readme = "README.md"

[tool.poetry.dependencies]
python = "<3.13,>=3.9"
pyserial = "^3.5"
python-can = "4.4.2"
argparse = "^1.4.0"
pyside6 = "^6.8.0"
nuitka = "^2.4.11"
black = "^24.10.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
