[tool.poetry]
name = "canviewer"
version = "0.0.1"
description = "CAN Sender GUI with slcand"
authors = ["tomixrm <chocolate0785lego@icloud.com>"]
license = "LGPL-2.1"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pyserial = "^3.5"
python-can = "4.5.0"
argparse = "^1.4.0"
pyside6 = {version = "^6.8.2.1", python = ">=3.10,<3.14"}
nuitka = "^2.6.8"
black = "^25.1.0"
mypy = "^1.15.0"
returns = "^0.24.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
